test lts

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -20,13 +20,13 @@ before_script:
 # - npm install -g sfdx-cli
 script:
 - node -v
-# - if [[ "$TRAVIS_PULL_REQUEST" = "false"]]; then
-#     sfdx force:lightning:test:install22;
-#   elif [[ $? > 0 ]]
-#   then
-#     npm install -g eslint;
-#   fi
-
-- if [[ "$TRAVIS_PULL_REQUEST" = "true" ]]; then
-    npm install -g sfdx-cli ;
+- if [[ "$TRAVIS_PULL_REQUEST" = "false" ]]; then
+    sfdx force:lightning:test:install22;
+  elif [[ $? > 0 ]]
+  then
+    npm install -g eslint;
   fi
+# - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then travis_retry npm install -g eslint; fi
+# - if [[ "$TRAVIS_PULL_REQUEST" = "true" ]]; then
+#     npm install -g sfdx-cli ;
+#   fi
